
set guifont=Andale\ Mono:h12
set noantialias
set lines=40 columns=90

set guioptions-=T
set guioptions-=L
set guioptions-=e
set guioptions-=r

set noruler
set nowrap
set number

colorscheme molokai

