
set guifont=Envy\ Code\ R\ for\ Powerline:h13 
"//set guifont=Andale\ Mono:h12
"//set noantialias
set lines=40 columns=90
set wrap

set guioptions-=T
set guioptions-=L
set guioptions-=e
set guioptions-=r

set noruler
set number

