
set nocompatible
set backspace=indent,eol,start
set modelines=0
set hidden

set nohlsearch
set incsearch
set laststatus=2

set autoindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

set ruler
set nonumber
set nowrap
set showmode
set scrolloff=8

set viminfo=""
set noswapfile
set nobackup
set nowb

set encoding=utf-8
set t_Co=256
syntax on
colorscheme molokai

"// basic skeleton for new html files
augroup html
   au BufNewFile *.html 0r ~/.vim/skel/html.skel
augroup end

"// and for new markdown files
augroup md
  au bufNewFile *.md 0r ~/.vim/skel/md.skel
augroup end

"// make vim recognize .md as markdown
au BufRead,BufNewFile *.md set filetype=markdown

let g:airline_detect_paste=1
let g:airline_theme='molokai'
"let g:airline_left_sep = '⮀'
"let g:airline_left_alt_sep = '⮁'
"let g:airline_right_sep = '⮂'
"let g:airline_right_alt_sep = '⮃'
"let g:airline_branch_prefix = '⭠'
"let g:airline_readonly_symbol = '⭤'
"let g:airline_linecolumn_prefix = '⭡'

