
set nocompatible
set backspace=indent,eol,start
set modelines=0
set hidden

set nohlsearch
set incsearch

set autoindent
"// set smartindent
"// set smarttab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

set ruler
set nonumber
set showmode
set scrolloff=8

set viminfo=""
set noswapfile
set nobackup
set nowb

syntax on
colorscheme molokai 

"// basic skeleton for new html files
augroup html
   au BufNewFile *.html 0r ~/.vim/skel/html.skel
augroup end

"// and for new markdown files
augroup md
	au bufNewFile *.md 0r ~/.vim/skel/md.skel
augroup end

"// make vim recognize .md as markdown
au BufRead,BufNewFile *.md set filetype=markdown


